# we need to refer the nodejs tasks in common folder 
# catalogue is one role
# common is another role 
# I need to import a task nodejs in catalogue 

- name: Install nodejs 
  ansible.builtin.import_role:
    name: common 
    tasks_from: nodejs 
    